-- =========================================================
-- Khin Early Bird - Supabase PostgreSQL Schema
-- Run this in your Supabase Project -> SQL Editor -> Run
-- =========================================================

-- 1. Jobs Table
CREATE TABLE IF NOT EXISTS public.jobs (
    id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    title TEXT NOT NULL,
    company TEXT NOT NULL,
    location TEXT,
    work_type TEXT DEFAULT 'Unknown',
    job_type TEXT DEFAULT 'Regular',
    role_category TEXT DEFAULT 'software_engineering',
    salary TEXT,
    description TEXT,
    apply_url TEXT,
    posted_date TEXT,
    extracted_at TEXT,
    status TEXT DEFAULT 'new'
);

-- 2. Evaluations Table
CREATE TABLE IF NOT EXISTS public.evaluations (
    job_id TEXT PRIMARY KEY REFERENCES public.jobs (id) ON DELETE CASCADE,
    match_score INTEGER DEFAULT 0,
    match_level TEXT DEFAULT 'Low Match',
    is_applicable BOOLEAN DEFAULT TRUE,
    match_reasons TEXT DEFAULT '[]',
    matched_skills TEXT DEFAULT '[]',
    missing_skills TEXT DEFAULT '[]',
    evaluated_at TEXT,
    ai_model TEXT DEFAULT 'tri-validator-ensemble-v1',
    gemini_score INTEGER DEFAULT 0,
    ml_score INTEGER DEFAULT 0,
    preference_score INTEGER DEFAULT 0,
    validators_passed INTEGER DEFAULT 0,
    validator_details TEXT DEFAULT '{}'
);

-- 3. Scrape Runs Table
CREATE TABLE IF NOT EXISTS public.scrape_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TEXT NOT NULL,
    finished_at TEXT,
    total_scraped INTEGER DEFAULT 0,
    total_new INTEGER DEFAULT 0,
    total_high_match INTEGER DEFAULT 0,
    status TEXT DEFAULT 'running',
    log TEXT
);

-- 4. App Settings Table
CREATE TABLE IF NOT EXISTS public.app_settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- Indexes for lightning fast queries & filtering
CREATE INDEX IF NOT EXISTS idx_jobs_status ON public.jobs (status);
CREATE INDEX IF NOT EXISTS idx_jobs_job_type ON public.jobs (job_type);
CREATE INDEX IF NOT EXISTS idx_jobs_role_category ON public.jobs (role_category);
CREATE INDEX IF NOT EXISTS idx_jobs_source ON public.jobs (source);
CREATE INDEX IF NOT EXISTS idx_evaluations_match_score ON public.evaluations (match_score DESC);
CREATE INDEX IF NOT EXISTS idx_evaluations_applicable ON public.evaluations (is_applicable);

-- Enable Row Level Security (RLS) with full anon access for the Early Bird client
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scrape_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

-- Allow read & write access with anon/service API keys
DROP POLICY IF EXISTS "Allow all for jobs" ON public.jobs;
CREATE POLICY "Allow all for jobs" ON public.jobs FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for evaluations" ON public.evaluations;
CREATE POLICY "Allow all for evaluations" ON public.evaluations FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for scrape_runs" ON public.scrape_runs;
CREATE POLICY "Allow all for scrape_runs" ON public.scrape_runs FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for app_settings" ON public.app_settings;
CREATE POLICY "Allow all for app_settings" ON public.app_settings FOR ALL USING (true) WITH CHECK (true);
